CCDNForum\ForumBundle\Entity\Topic:
    properties:
        board:
            - NotNull: { groups: [topic] }
        title:
            - Type: { type: string, groups: [topic] }
            - NotBlank: { groups: [topic] }
            - MinLength: { limit: 10, groups: [topic] }
            - MaxLength: { limit: 255, groups: [topic] }

CCDNForum\ForumBundle\Entity\Post:
    properties:
        body:
            - Type: { type: string, groups: [post] }
            - NotBlank: { groups: [post] }
            - MinLength: { limit: 15, groups: [post] }
            - MaxLength: { limit: 30000, groups: [post] }
